Update to Swift 4.2
Expensify/TTGSnackbar pull request #6
Opened 2018-11-19 21:22 UTC by msweet168

Please review @migfabio
Attn: @Expensify/mobile

Currently, TTGSnackbar is written in Swift 4.0 which has since been replaced with Swift 4.2. This PR updates to Swift 4.2 syntax so the pod can be updated in the main Expensify app.

2018-11-19 22:01 UTC, capezzbr commented
I'd also pull the latest changes from the main repo now that you are at it (unless there are too many conflicts)

2018-11-20 11:00 UTC, migfabio commented
I agree with @capezzbr 
Can you try to pull from the upstream? This is a link that could help you https://help.github.com/articles/syncing-a-fork/

2018-11-20 11:19 UTC, migfabio requested changes

2018-11-20 11:19 UTC, migfabio commented on TTGSnackbar/TTGSnackbar.swift
> +            actionButton.setTitle(actionText, for: UIControl.State())
use `.normal` instead of `UIControl.State()`.
this is valid everywhere

2018-11-20 11:19 UTC, migfabio commented on TTGSnackbar/TTGSnackbar.swift
> +        RunLoop.main.add(dismissTimer!, forMode: RunLoop.Mode.common)
nab, use `.common`

2018-11-20 11:19 UTC, migfabio commented on TTGSnackbar/TTGSnackbar.swift
> +            if window.windowLevel == UIWindow.Level.normal {
nab, use `.normal`

2018-11-20 11:19 UTC, migfabio commented on TTGSnackbar/TTGSnackbar.swift
> +            options: NSLayoutConstraint.FormatOptions(rawValue: 0),
nab, there is no need to do `NSLayoutFormatOptions(rawValue: 0)`. rather just type in `[]`

2018-11-26 21:22 UTC, msweet168 commented
I have updated @migfabio 's suggestions. I have decided not to merge from the main upstream fork. There are many merge conflicts with the base project and pod files which Xcode's version editor cannot even read. I don't feel it is worth it to also risk the working state of the pod by updating since nothing is deprecated and it works how we want it to. Let me know if you have any questions or comments about this!

2018-11-28 11:08 UTC, migfabio approved these changes
Okay, if it's a pain and not worth it, this LGTM 👍

2018-11-28 11:09 UTC, merged